In [3]:
import pandas as pd
import fractions
import random
data = {'prompts': [], 'response': []}
words = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]
def decimal_to_word(decimal):
    if '.' not in str(decimal):
        return words[min(int(decimal), 9)] 
    whole_part, decimal_part = str(decimal).split('.')
    if int(whole_part) > 0:
        whole_word = words[min(int(whole_part), 9)] + " point "  
    else:
        whole_word = "zero point "
    decimal_word = ' '.join([words[min(int(digit), 9)] for digit in decimal_part])  
    
    return whole_word + decimal_word                          
def word_to_decimal(word_str):
    word_mapping = {
        'zero': 0, 'one': 1, 'two': 2, 'three': 3, 'four': 4,
        'five': 5, 'six': 6, 'seven': 7, 'eight': 8, 'nine': 9,
    }

    if 'point' not in word_str:
        return word_mapping[word_str]
    
    whole_part, fractional_part = word_str.split(' point ')
    fractional_value = sum(word_mapping[digit] * (0.1 ** (idx + 1)) for idx, digit in enumerate(fractional_part.split()))

    return word_mapping[whole_part] + fractional_value
def evaluate_equivalence(items):
    """Evaluate if all items in the list are equivalent in value."""
    values = []
    for item in items:
        if "%" in item:
            values.append(round(float(item.rstrip('%')) / 100, 5))
        elif "/" in item:
            frac = fractions.Fraction(item)
            values.append(round(float(frac), 5))
        elif item.replace('.', '', 1).isdigit():
            values.append(round(float(item), 5))
        else:
            values.append(round(word_to_decimal(item), 5))
    return len(set(values)) == 1
count = 0
while count < 10000:
    num_items = random.randint(2, 4) 
    items = []
    
    # 1. Select a random base value
    numerator = random.randint(1, 10)
    denominator = random.randint(1, 10)
    frac = fractions.Fraction(numerator, denominator)
    decimal_base = float(frac)
    
    # 2. Randomly generate first format of this base value
    format_type = random.choice(["percentage", "fraction", "decimal", "word"])
    if format_type == "percentage":
        items.append(f'{decimal_base * 100:.2f}%')
    elif format_type == "fraction":
        items.append(f'{frac}')
    elif format_type == "decimal":
        items.append(f'{decimal_base:.2f}')
    else: 
        items.append(decimal_to_word(decimal_base))
    
    # 3. Use the base value to generate the other items in different formats
    available_formats = ["percentage", "fraction", "decimal", "word"]
    available_formats.remove(format_type)
    
    for _ in range(num_items - 1):
        format_type = random.choice(available_formats)
        available_formats.remove(format_type)
        
        if format_type == "percentage":
            items.append(f'{decimal_base * 100:.2f}%')
        elif format_type == "fraction":
            items.append(f'{frac}')
        elif format_type == "decimal":
            items.append(f'{decimal_base:.2f}')
        else: 
            items.append(decimal_to_word(decimal_base))
    
    statement = '[' + ', '.join(['"' + item + '"' for item in items]) + ']'
    
    data['prompts'].append(statement)
    data['response'].append(evaluate_equivalence(items))
    count += 1

df = pd.DataFrame(data)
df2 = df.sample(50)
df2['prompts'] = df2['prompts'].str.replace('"', "'")
df2

                                                prompts  response
4851        ['500.00%', '5.00', 'five point zero', '5']      True
3084                    ['2', '2.00', 'two point zero']      True
6810                                ['2.00', '200.00%']      True
4377  ['5/3', '166.67%', '1.67', 'one point six six ...     False
8162  ['2/3', 'zero point six six six six six six si...      True
956   ['zero point eight three three three three thr...     False
1491                           ['5', '5.00', '500.00%']      True
9269                         ['1.00', 'one point zero']      True
2492  ['zero point three three three three three thr...     False
1776                  ['5/2', '2.50', 'two point five']      True
2948                         ['1.50', 'one point five']      True
4739                                 ['125.00%', '5/4']      True
2860       ['2/5', '40.00%', '0.40', 'zero point four']      True
8052                        ['4/5', 'zero point eight']      True
8916                                ['100.00%', '1.00']      True
9978  ['1.11', 'one point one one one one one one on...     False
4681                                ['200.00%', '2.00']      True
3658       ['two point five', '2.50', '250.00%', '5/2']      True
469   ['2.33', '7/3', '233.33%', 'two point three th...     False
4961  ['one point two eight five seven one four two ...     False
5426  ['55.56%', 'zero point five five five five fiv...     False
3362                      ['100.00%', 'one point zero']      True
6647        ['400.00%', 'four point zero', '4', '4.00']      True
8389                                    ['0.20', '1/5']      True
1052                                   ['0.30', '3/10']      True
467                           ['33.33%', '1/3', '0.33']     False
1373                  ['3.00', '3', 'three point zero']      True
6651  ['2/9', '22.22%', 'zero point two two two two ...     False
4832       ['one point five', '150.00%', '3/2', '1.50']      True
6055  ['116.67%', 'one point one six six six six six...     False
5585                                    ['1/4', '0.25']      True
3934          ['1.25', 'one point two five', '125.00%']      True
4421                                    ['1/3', '0.33']     False
7880                          ['88.89%', '8/9', '0.89']     False
5499  ['75.00%', '3/4', 'zero point seven five', '0....      True
9339  ['zero point seven seven seven seven seven sev...     False
3243              ['50.00%', '0.50', 'zero point five']      True
2232  ['55.56%', 'zero point five five five five fiv...     False
8221                          ['20.00%', '0.20', '1/5']      True
1026  ['zero point eight five seven one four two eig...     False
8746         ['100.00%', '1.00', 'one point zero', '1']      True
2780                                    ['0.60', '3/5']      True
4523  ['1.67', 'one point six six six six six six si...     False
4251                                    ['0.56', '5/9']     False
1742                      ['50.00%', 'zero point five']      True
5647                         ['1.67', '5/3', '166.67%']     False
1824                                ['7.00', '700.00%']      True
7347  ['3/8', '37.50%', '0.38', 'zero point three se...     False
2512                                   ['1', '100.00%']      True
4547               ['zero point five', '50.00%', '1/2']      True